# Technical Challenge ! Custiomers and Orders - The lifeblood of any business!

This notebook depends on two data files: customers.scv and orders.csv. These files are hosted in the cloud (or Github), so for simplicity, we are providing you with the code to download and save the two files in a folder called 'sample_data' which lives within this notebook session (not on your local computer nor Google Drive).

![sample_data folder in notebook session](https://raw.githubusercontent.com/anyoneai/notebooks/main/customers_and_orders/images/sample_data_folder.png)

Please execute the first code snippet before moving to the rest of the exercise as this code will import the data from the files for you to be able to execute the rest of the exercise.

Remember as we said in the previous lecture, you have to save this notebook into your Google Drive by going to menu File/Save a Copy In Drive, or clicking in the button "Copy to Drive". This way, you will not lose any work you've done and the file will persist with your latest changes in your Google Drive. Also we recommend you to rename your .ipynb in your Google Drive, so you can easily find it in the future.

In [1]:
import requests

def import_data_files():
  r = requests.get('https://raw.githubusercontent.com/anyoneai/notebooks/main/customers_and_orders/data/customers.csv')
  with open('./sample_data/customers.csv', 'wb') as f:
    f.write(r.content)

  r = requests.get('https://raw.githubusercontent.com/anyoneai/notebooks/main/customers_and_orders/data/orders.csv')
  with open('./sample_data/orders.csv', 'wb') as f:
    f.write(r.content)

import_data_files()
print("Customers and orders CSV files have been added './sample_data'")

Customers and orders CSV files have been added './sample_data'

# Exercise 1: Processing Customers data (difficulty medium)

The sample customer data in 'customers.csv' file has just 5 columns: CustomerId, First Name, Last Name, City and State

![Data sample](https://raw.githubusercontent.com/anyoneai/notebooks/main/customers_and_orders/images/customers.png)

We strongly recommend that you complete from the [Prep Course: Intro to Python](https://colab.research.google.com/github/anyoneai/notebooks/blob/main/python3_crash_course.ipynb) the following section:
- Section 7: File I/O (to understand how to read CSV file)
- Section 6: For Loop (to navigate the contents of the CSV file)
- Section 5: Tuples, Lists, and Dictionaries (to manipulate the data of the CSV file)

With this, we hope you can complete this exercise successfully. Although if you want to solve this with libraries or any other way, you are welcome to do it your way.

*Hint:* We advise you to take a look at the data before you start.
**if you want to manually take a look at the data before you start, please see the content of the data [here](https://github.com/anyoneai/notebooks/blob/main/customers_and_orders/data/customers.csv).

*Hint*: There are many ways to do this exercise you can do your own, although here's some help. You can solve this exercise reading and parsing CSV files, structuring data into dictionaries, and using for loops to navigate the contents

*Hint*: Also, keep in mind that data might not be clean and you might have to figure out how to deal with that data from the code, without having to modify the data source.

Below are the 5 questions you'll have to answer to pass the evaluation:

**Question 1:** How many customers are in the file?
(as help, we have added some comments and starter code to help you structure the solution)

In [16]:
from os.path import exists
import csv

# check if file can be found and open the file
count = 0
datafile = "./sample_data/customers.csv"
if not exists(datafile):
  raise SystemExit("You should run the first code cell and download the dataset files!")

# customers file is in the sample_data folder and can be opened.
# Using csv reader is one way of dealing with the file
# but it's up to you how you want to proceed
with open(datafile, 'r') as fl:
  csvreader = csv.reader(fl, delimiter=',')
  for row in csvreader:
    print("Row: %s | %s" % (row[0], row[1]))
    count = count+1
  # loop through the rows and count etc. THE REST IS UP TO YOU!
print("There are: ", count, "customers")

Row: CustomerID | FirstName
Row: 6192 | Randi
Row: 5100595 | Christopher
Row: 1902451 | Elvis
Row: 1906377 | Jose
Row: 1902406 | Scott
Row: 22445 | Erin
Row: 11042 | Stephen
Row: 1500181 | Kari
Row: 4300371 | Edsel
Row: 4301400 | Corey
Row: 701684 | Shelton
Row: 4302023 | Matteo
Row: 9236 | Ralph
Row: 1906377 | Jose
Row: 5172200 | Andrew
Row: 5173013 | Ivanna
Row: 1500181 | Kari
Row: 1905150 | Mark
Row: 4302052 | Michelle
Row: 5370538 | Samantha
Row: 4300438 | Rhea
Row: 1907428 | Josue
Row: 5370863 | Angel
Row: 5173966 | Connor
Row: 5768 | Leonard
Row: 1900610 | Scott
Row: 4300254 | Sarah
Row: 5100330 | Rosaline
Row: 1904538 | Terry
Row: 902251 | Mary
Row: 1500339 | Robert
Row: 1909384 | Maria
Row: 5172086 | Khalil
Row: 1904932 | Desirea
Row: 5370771 | Prince
Row: 5370253 | Astrid
Row: 5370896 | BÃ©atrice
Row: 5173881 | Faith
Row: 5173981 | Hector
Row: 900635 | Antonio
Row: 5971 | Craig
Row: 5774 | Mary
Row: 5955 | Merrily
Row: 8462 | Miguel
Row: 5053 | Doe
Row: 2300276 | Jessy
Row: 5889 | Stephen
Row: 5101470 | George
Row: 1909705 | Kevin
Row: 5172982 | Erika
Row: 5173868 | Geneva
Row: 5173800 | Angelina
Row: 5173885 | Steven
Row: 4302129 | Carla
Row: 5174054 | Alicia
Row: 900590 | Christina
Row: 5370557 | Guchul
Row: 5173686 | Jose Luis
Row: 5572 | Todd
Row: 5371026 | DR. Marina
Row: 5370673 | Tyler
Row: 5173982 | Teale
Row: 5173648 | Melba
Row: 5370404 | Amanda
Row: 5370527 | Patrick
Row: 5370986 | Elizabeth
Row: 5370856 | Stephan
Row: 902503 | Miguel
Row: 903743 | Carmen
Row: 7553 | Al
Row: 5101829 | Mariano
Row: 4301487 | Manik Lal
Row: 5393076 | Jennifer
Row: 1903965 | Christina
Row: 5415323 | Miles
Row: 1907925 | Jordan
Row: 4300081 | Richard
Row: 5370298 | Alma
Row: 5370969 | David
Row: 5371016 | Conner
Row: 5415122 | Dorothy
Row: 5078 | Barbara
Row: 1904932 | Desirea
Row: 5173872 | Antonio
Row: 5370196 | Andrew
Row: 6194 | Lorraine
Row: 900590 | Christina
Row: 5370422 | Emma
Row: 5173650 | Sergio
Row: 5415114 | Adriana
Row: 5972 | Paul
Row: 5415162 | Terah
Row: 5415228 | Kimberly
Row: 5572 | Todd
Row: 5053 | Doe
Row: 5053 | Doe
Row: 1901469 | Marneil
Row: 5774 | Mary
Row: 701684 | Shelton
Row: 900569 | Judith
Row: 1902451 | Elvis
Row: 7639 | Blake
Row: 8091 | Anne
Row: 5173998 | Charles
Row: 5370786 | Kathryn
Row: 1500339 | Robert
Row: 703330 | Jose
Row: 4300670 | Jina
Row: 5945 | Pam
Row: 4301059 | Natalie
Row: 5463 |  Freddy
Row: 5370200 | Thomas
Row: 5370247 | Sherry
Row: 5431 | Jorge
Row: 5227 | Linda
Row: 4300754 | Franco
Row: 5370388 | Sara
Row: 701258 | Mark
Row: 1904821 | Liz
Row: 5415279 | Dawn
Row: 5415211 | Tristan
Row: 5415400 | Giselle
Row: 5415391 | Diana
Row: 5415361 | Jason
Row: 5415384 | Marty
Row: 5415409 | Tamecka
Row: 5415411 | Teresa
Row: 1903794 | Rhianna
Row: 5415445 | Joseph
Row: 5172200 | Andrew
Row: 5415461 | Isiah
Row: 5415466 | Yusuf
Row: 5415452 | Gaby
Row: 5415502 | Geovanny
Row: 5415329 | Amir
Row: 5415395 | Melissa
Row: 1908941 | Cesar
Row: 5370504 | Brian
Row: 1909384 | Maria
Row: 1900610 | Scott
Row: 4301179 | Janette
Row: 5014 | Teresa
Row: 703330 | Jose
Row: 1907812 | Mireille
Row: 1906528 | Michael
Row: 6177 | Elizabeth
Row: 9387 | Mohan
Row: 701258 | Mark
Row: 1903127 | Ralph
Row: 1905606 | Brenda
Row: 2300256 | George
Row: 5172092 | Michelle
Row: 4301147 | Vilma
Row: 1909384 | Maria
Row: 5172728 | Maria
Row: 700331 | Perry
Row: 1907770 | Garret
Row: 4302023 | Matteo
Row: 5101506 | Julianne
Row: 3500018 | Wayne
Row: 5776 | Zeferino
Row: 5076 | Nicki
Row: 5808 | Stanley
Row: 5901 | Jila Miandoab
Row: 1906350 | Carrie
Row: 5701 | Aaron
Row: 4301198 | Hipolito
Row: 5172534 | Vicente
Row: 5173438 | April
Row: 5173013 | Ivanna
Row: 703136 | Sean
Row: 5172443 | Brandon
Row: 703804 | Walter
Row: 5370110 | Sachiko
Row: 5173856 | Pocholo Luis
Row: 1905938 | JJ
Row: 4700094 | Jeff
Row: 1900588 | Gayle
Row: 6131 | Beverley
Row: 902639 | John
Row: 7901 | Juzo
Row: 703561 | Anthony
Row: 1909346 | Monica Ofelia
Row: 5173073 | Trenecca
Row: 1905938 | JJ
Row: 4301117 | Natalie
Row: 5101127 | Michael
Row: 5173927 | Jackelyn
Row: 5173962 | Catina
Row: 4301117 | Natalie
Row: 5173498 | Tristan
Row: 5173196 | Kaohai
Row: 5370196 | Andrew
Row: 5173788 | Jeff
Row: 5370101 | Maria De Jesus
Row: 5370251 | Jose
Row: 5174063 | Albert
Row: 5371053 | Khureltsetseg
Row: 5370211 | Kimberly
Row: 5370268 | Valerie
Row: 5370647 | Jadira
Row: 900258 | Bully
Row: 5756 | Edna
Row: 1500569 | Cecilio
Row: 4300858 | Diana
Row: 4301696 | Rachel
Row: 5100834 | Isabel
Row: 5100984 | Fransico
Row: 700294 | Simon
Row: 5172598 | Emma
Row: 5173018 | Vincent
Row: 4301159 | Rajendra
Row: 5173569 | Alicia
Row: 5173135 | Marco
Row: 5173901 | Natalie
Row: 5173018 | Vincent
Row: 5174004 | John
Row: 5370706 | Katrina
Row: 1904527 | Carolyn
Row: 5227 | Linda
Row: 5173895 | Giancarlo
Row: 5370317 | Valerie
Row: 5370216 | Iliana
Row: 5370985 | Gabriela
Row: 5370163 | Alessandra
Row: 5370983 | Michael
Row: 5415089 | Isabelle
Row: 4301487 | Manik Lal
Row: 5415171 | Dena
Row: 903743 | Carmen
Row: 701419 | Milton
Row: 5078 | Barbara
Row: 5370278 | Brittany
Row: 5370719 | James
Row: 5173938 | Eltidio
Row: 701684 | Shelton
Row: 5370142 | Junecheol
Row: 5463 |  Freddy
Row: 1907925 | Jordan
Row: 4301217 | Maria
Row: 5370378 | Amalia
Row: 20850 | Marcy
Row: 1908934 | Sara
Row: 9387 | Mohan
Row: 6177 | Elizabeth
Row: 6177 | Elizabeth
Row: 5370458 | Alyssa
Row: 5370474 | Andie
Row: 5100785 | Yoona
Row: 5371026 | DR. Marina
Row: 5415113 | Kelsey
Row: 7812 | Andre
Row: 5370757 | Michelle
Row: 4300695 | Diane
Row: 5463 |  Freddy
Row: 4301117 | Natalie
Row: 700771 | Cida
Row: 1903794 | Rhianna
Row: 1905150 | Mark
Row: 902139 | Ernie
Row: 5972 | Paul
Row: 10986 | Bill
Row: 10986 | Bill
Row: 1904538 | Terry
Row: 703330 | Jose
Row: 5415331 | Teagan
Row: 5415402 | Phyllisa
Row: 5415416 | Paris
Row: 5173749 | Abigail
Row: 5415434 | Lucas
Row: 902503 | Miguel
Row: 23898 | Masao
Row: 5078 | Barbara
Row: 5431 | Jorge
Row: 1909700 | Robert
Row: 4302187 | Diana
Row: 5430 | James
Row: 701419 | Milton
Row: 5100812 | John
Row: 5814 | Robert
Row: 5782 | Barbara
Row: 4301217 | Maria
Row: 1903078 | Francisco
Row: 5280 | Annette
Row: 902536 | Heather
Row: 5100007 | Paul
Row: 11481 | Randy
Row: 5464 | Juan
Row: 5172859 | Maria
Row: 1904133 | Luis
Row: 5173158 | Ines
Row: 1908177 | Najiba
Row: 5173778 | David
Row: 4300670 | Jina
Row: 5173939 | Lisa Marie
Row: 900070 | Donald
Row: 1904479 | Stuart
Row: 23107 | David
Row: 1500028 | Rachelle
Row: 1907160 | Mohamed
Row: 1904529 | Elizabeth
Row: 5616 | Francisco
Row: 5945 | Pam
Row: 1904438 | Paul
Row: 5126048 | Renee
Row: 5172376 | James
Row: 5172601 | Melissa
Row: 5172644 | Martha
Row: 5172760 | Winston
Row: 901063 | Dermot
Row: 22827 | Joe
Row: 5370315 | Erin
Row: 5100779 | Daniel
Row: 4301968 | Thande
Row: 20850 | Marcy
Row: 5100363 | Lindsey
Row: 1905150 | Mark
Row: 900635 | Antonio
Row: 5424 | Lynne A.
Row: 5173506 | Joseph
Row: 1903426 | Edward
Row: 5172786 | Michael
Row: 1905380 | Rosa
Row: 20532 | Lourdes
Row: 5415325 | Robert
Row: 1909369 | Sophie
Row: 5172284 | Joel
Row: 900569 | Judith
Row: 5173287 | Jennifer
Row: 5100330 | Rosaline
Row: 5174021 | Mariely
Row: 5370863 | Angel
Row: 5172760 | Winston
Row: 5370134 | Darwin
Row: 10986 | Bill
Row: 5100185 | Angie
Row: 903601 | Chris
Row: 11321 | Andrew
Row: 4300928 | Miguel
Row: 1907083 | Jonathan
Row: 5172365 | Nancy
Row: 4301362 | Andrew
Row: 5172799 | Jamie
Row: 7812 | Andre
Row: 5173918 | Cecilia
Row: 5173800 | Angelina
Row: 5173969 | Miguel
Row: 5100785 | Yoona
Row: 5370205 | Monica
Row: 5173783 | Elena
Row: 4301362 | Andrew
Row: 5370415 | Tristan
Row: 5172656 | Somerset
Row: 5173842 | Anthony
Row: 5174027 | Long
Row: 5370482 | Valentina
Row: 1901046 | Reginald
Row: 5370547 | Alan
Row: 5370602 | Jasleen
Row: 5415249 | Colleen
Row: 5370846 | Desiree
Row: 5173904 | Charles
Row: 5370655 | Elias
Row: 5370630 | Alice
Row: 5415141 | Emma
Row: 5415175 | Jeannae
Row: 5415182 | Ronnie
Row: 1904886 | Alice
Row: 901786 | Eduardo
Row: 5173844 | Tiffany
Row: 5370649 | Eric
Row: 23898 | Masao
Row: 902536 | Heather
Row: 1904133 | Luis
Row: 5173877 | Jordan
Row: 5370884 | Nicole
Row: 700771 | Cida
Row: 902139 | Ernie
Row: 703804 | Walter
Row: 5370475 | Roxy
Row: 5173650 | Sergio
Row: 5126069 | Susie
Row: 5370758 | Xiaoyu
Row: 10986 | Bill
Row: 1907428 | Josue
Row: 1907812 | Mireille
Row: 4300754 | Franco
Row: 5945 | Pam
Row: 23898 | Masao
Row: 700771 | Cida
Row: 901063 | Dermot
Row: 1907141 | Kristen
Row: 5415286 | Jonathan
Row: 5415427 | Kacie
Row: 5415436 | Genevieve
Row: 5415443 | Isabel
Row: 701419 | Milton
Row: 5415407 | Luiza
Row: 5415422 | Adam
Row: 5415424 | Paula
Row: 5415456 | Raquel
Row: 5415457 | Shawn
Row: 5415472 | Joseph
Row: 5370200 | Thomas
Row: 4301117 | Natalie
Row: 5415470 | Kerwin
Row: 5415484 | Arely
Row: 5415486 | Jillian
Row: 6194 | Lorraine
Row: 8091 | Anne
Row: 5365 | Richard
Row: 7639 | Blake
Row: 6196 | Cecilia
Row: 8259 | Josh
Row: 6144 | Roger
Row: 5100779 | Daniel
Row: 1901506 | Gerald
Row: 19096 | Joe
Row: 2300266 | Josh
Row: 5710 | Samuel
Row: 5172086 | Khalil
Row: 902139 | Ernie
Row: 5173415 | Max
Row: 700771 | Cida
Row: 1900709 | Shaheen
Row: 5370671 | Maria
Row: 703804 | Walter
Row: 4302023 | Matteo
Row: 5126060 | Behzad
Row: 4300295 | Erin
Row: 9612 | Diana
Row: 5172337 | Jae Zee
Row: 1908934 | Sara
Row: 4300840 | Yousof
Row: 900329 | Hector
Row: 5172487 | Artem
Row: 4700014 | Kenneth
Row: 5100605 | Simona
Row: 900879 | Keiji
Row: 4301885 | Abdul
Row: 5100721 | Victor
Row: 5172133 | Jeremiah
Row: 5101748 | Donna
Row: 5068 | Maureen
Row: 1907259 | Rosa
Row: 1904400 | Salvador G
Row: 20471 | Janice
Row: 5446 | Tom
Row: 4300081 | Richard
Row: 1900805 | Tereso
Row: 5101829 | Mariano
Row: 4301100 | George
Row: 5172491 | Leon
Row: 4300081 | Richard
Row: 3900068 | Jessica
Row: 5463 |  Freddy
Row: 5946 | Mark
Row: 5172908 | Julie
Row: 5173893 | Jasmine
Row: 5172643 | Nicole
Row: 5370086 | Aida
Row: 5173498 | Tristan
Row: 5370111 | Zoe
Row: 5370159 | Jade
Row: 5173989 | James
Row: 1901469 | Marneil
Row: 5572 | Todd
Row: 5721 | Janet
Row: 5101304 | Emanuel
Row: 4301827 | Hector
Row: 14564 | Louis
Row: 5172865 | Christa
Row: 5172680 | Frances
Row: 5100984 | Fransico
Row: 5370173 | Jared
Row: 11321 | Andrew
Row: 5370446 | Brooke
Row: 5370378 | Amalia
Row: 4301400 | Corey
Row: 5371030 | Angela
Row: 5173938 | Eltidio
Row: 5173613 | Arvin
Row: 5173749 | Abigail
Row: 1909369 | Sophie
Row: 5173928 | Sean
Row: 5463 |  Freddy
Row: 1907925 | Jordan
Row: 5173875 | Sara
Row: 5370599 | Valeria
Row: 20471 | Janice
Row: 8404 | Maria
Row: 7901 | Juzo
Row: 5446 | Tom
Row: 5370415 | Tristan
Row: 8259 | Josh
Row: 1900610 | Scott
Row: 5370329 | Shoji
Row: 1909384 | Maria
Row: 5100834 | Isabel
Row: 903601 | Chris
Row: 10986 | Bill
Row: 5370347 | Melissa
Row: 5370163 | Alessandra
Row: 4301885 | Abdul
Row: 23107 | David
Row: 1909369 | Sophie
Row: 1904133 | Luis
Row: 5431 | Jorge
Row: 5415350 | Chris
Row: 5415420 | Christine
Row: 5415425 | Michele
Row: 1904821 | Liz
Row: 5415441 | Brandon
Row: 5415450 | Lavinia
Row: 5415318 | Karen
Row: 5415468 | Chauntelle
Row: 5415477 | Cherrod
Row: 903601 | Chris
Row: 3900068 | Jessica
Row: 5415337 | Ezgi
Row: 5415404 | Michael
Row: 5415405 | Erika
Row: 5415423 | Teja
Row: 5173895 | Giancarlo
Row: 5415438 | Gray
Row: 4301754 | Lorelei
Row: 5415455 | Larry
Row: 5415270 | Kiersten
Row: 5415474 | Julio
Row: 5415428 | Karen
Row: 5370111 | Zoe
Row: 5415433 | Brandon
Row: 5415444 | Edward
Row: 5415453 | Susan
Row: 5415503 | Alison
Row: 5415397 | Gabriela
Row: 5415414 | Tobin
Row: 5415382 | Roland
Row: 5415429 | Bob
Row: 5415430 | Aaron
Row: 5415198 | Catherine
Row: 5415431 | Judy
Row: 5415432 | Luz
Row: 5415232 | Guillermo
Row: 5415464 | Lisa
Row: 5415413 | Loukas
Row: 5415398 | Natasha
Row: 5415415 | Vivian
Row: 5415462 | Patricia
Row: 5415463 | Juvencio
Row: 1904133 | Luis
Row: 1904886 | Alice
Row: 5415421 | Yuanyuan
Row: 5415471 | Kelley
Row: 4301100 | George
Row: 5415401 | Gabriela
Row: 5415410 | Jeonghyun
Row: 5415426 | Sequoia
Row: 5415435 | Susanna
Row: 5415478 | Vanessa
Row: 5415451 | Tarah
Row: 4300670 | Jina
Row: 4302052 | Michelle
Row: 5415394 | Barry
Row: 5415458 | Monica
Row: 5415469 | Robyn
Row: 5415476 | Steven
Row: 5415498 | Ayman
Row: 5415499 | Mariella
Row: 5415418 | Rhonda
Row: 5415459 | Franchesca
Row: 5415475 | Ruriko
Row: 5415500 | Volha
Row: 5415406 | Melodie
Row: 5415087 | Rocio
Row: 5415437 | Michael
Row: 5415440 | David
Row: 5415439 | Jovanny
Row: 5415473 | Darrick
Row: 702407 | Steven
Row: 5415285 | Barry
Row: 5415403 | Jacqueline
Row: 5415408 | Raul
Row: 5415419 | Juan
Row: 5415442 | Scott
Row: 5415460 | Shayden
Row: 5415467 | Maria
Row: 5415483 | Victor
Row: 5415485 | Garrett
Row: 5415449 | Jesseca
Row: 5415447 | Fernando
Row: 5415399 | Charlene
Row: 5415412 | Rita
Row: 5415379 | Gaylord Jordan
Row: 5415362 | Alan
Row: 5415446 | Aaron
Row: 5415448 | Edgardo
Row: 5415365 | Trinity
Row: 5415465 | Kisona
Row: 5415345 | Lawrence
Row: 5415481 | John
Row: 5415482 | Phillip
There are:  603 customers

**Question 2:** In how many different states do the customers live in?

In [27]:
# open file and init vars
data = "./sample_data/customers.csv"
states = set()
if not exists(datafile):
  raise SystemExit("You should run the first code cell and download the dataset files!")

with open(data, "r") as myfile:
  csvreader = csv.reader(myfile, delimiter=",")
  next(csvreader)
  for row in csvreader:
    state = row[4].strip()
    states.add(state)
print("Number of states: ", len(states))
print("Different states: ", states)
# evaluate the contents of the file

Number of states:  15
Different states:  {'ID', 'NH', 'NV', 'IN', 'FL', 'WA', 'NM', 'OR', 'MA', 'TX', 'CO', 'Ca', 'AZ', 'CA', 'UT'}

**Question 3** What is the state with most customers?

In [48]:
from collections import Counter
# open file and init vars
data = "./sample_data/customers.csv"
count_states = Counter()

if not exists(datafile):
  raise SystemExit("You should run the first code cell and download the dataset files!")

with open(data, "r") as myfile:
  csvreader = csv.reader(myfile, delimiter=",")
  next(csvreader)
  for row in csvreader:
    state = row[4].strip()
    count_states[state] +=1

common_state, quantity = count_states.most_common(1)[0]
print("state with more customers is: ", common_state)
# evaluate the contents of the file

state with more customers is:  CA

**Question 4** What is the state with the least customers?

In [50]:
# open file and init vars
from collections import Counter
# open file and init vars
data = "./sample_data/customers.csv"
count_states = Counter()

if not exists(datafile):
  raise SystemExit("You should run the first code cell and download the dataset files!")

with open(data, "r") as myfile:
  csvreader = csv.reader(myfile, delimiter=",")
  next(csvreader)
  for row in csvreader:
    state = row[4].strip()
    count_states[state] +=1

common_state, quantity = count_states.most_common()[-1]
print("state with less customers is: ", common_state)
# evaluate the contents of the file

state with less customers is:  IN

**Question 5:** What is the most common last name?

In [52]:
# open file and init vars
from collections import Counter
data = "./sample_data/customers.csv"
count_last_name = Counter()

if not exists(datafile):
  raise SystemExit("You should run the first code cell and download the dataset files!")

with open(data, "r") as myfile:
  csvreader = csv.reader(myfile, delimiter=",")
  next(csvreader)
  for row in csvreader:
    last_name = row[2].strip()
    count_last_name[last_name] +=1

common_last_name, quantity = count_last_name.most_common(1)[0]
print("More common lastname is: ", common_last_name)

More common lastname is:  Smith

# Exercise 2: Processing Orders data (difficulty high)

The second sample files contains orders placed by customers from the first file. Be careful, this file has many rows and you most likely should not print the contents of the whole file.

The file contains the following columns: CustomerID, OrderID, Date, OrderTotal, ProductName, Price

![Data sample](https://raw.githubusercontent.com/anyoneai/notebooks/main/customers_and_orders/images/orders.png)

*Hint:* We advise you to take a look at the data before you start.
**if you want to manually take a look at the data before you start, please see the content of the data [here](https://raw.githubusercontent.com/anyoneai/notebooks/main/customers_and_orders/data/orders.csv).

*Hint*: There are many ways to do this exercise you can do your own, although here's some help. You can solve this exercise reading and parsing CSV files, structuring data into dictionaries, and using for loops to navigate the contents

*Hint*: Also, the data is not clean and you will have to figure out how to deal with that data from the code, without having to modify the data source.



**Question #1:** How many unique orders are in the orders.csv file?

**Question #2:** What is the average number of items per order (rounded to two decimal places)?

**Question #3:** What is the highest number of items per order?

**Question #4:** What is the number of orders placed in October 2021?

**Question #5:** Which customer spent the most amount of money in 2021?

**Question #6:** Historically, what is the best month for sales?

Once you get your answers, remember to go back to the course and introduce them in the multiple choice quiz

In [ ]:
# open and evaluate orders.csv

# Finished!

Hope this was not too difficult and slicing and dicing the datasets was some fun. Now head on back to the course and provide the answers to the questions from this exercise.